---
- name: Gather OS specific variables
  include_vars: "{{ lookup('first_found', java_params) }}"

- name: Set java_home
  set_fact:
    java_home: "{{ java_home_default }}"

- block:
  - block:
    - name: Setup debian
      include_tasks: debian.yml
    when: java_install

  - name: Set java default profile
    copy:
      content: |
        #!/bin/sh
        export JAVA_HOME={{ java_home }}
        export PATH=$JAVA_HOME/bin:$PATH
      dest: /etc/profile.d/java.sh
      backup: yes
      mode: 0644
  when: not java_skip_dependencies
