---

- name: Gather OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution|lower }}-{{ ansible_distribution_version|lower }}.yml"
    - "../vars/{{ ansible_distribution|lower }}.yml"
    - "../vars/{{ ansible_os_family|lower }}.yml"
    - "../vars/defaults.yml"

- name: Setup debian
  include_tasks: debian.yml